<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DoctorAppointmentSystem.Core\DoctorAppointmentSystem.Core.csproj" />
    <ProjectReference Include="..\DoctorAppointmentSystem.Infrastructure\DoctorAppointmentSystem.Infrastructure.csproj" />
    <ProjectReference Include="..\DoctorAppointmentSystem.ServiceDefaults\DoctorAppointmentSystem.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

</Project>